source 'https://supermarket.chef.io'

cookbook 'yum'
cookbook 'git'
cookbook 'mysql'
cookbook 'httpd', git: 'https://github.com/chef-cookbooks/httpd.git'
cookbook 'phpenv', git: 'https://github.com/Numergy/phpenv-cookbook'
cookbook 'motd', git: 'https://github.com/linyows/motd-cookbook.git'
cookbook 'consul', git: 'https://github.com/linyows/consul-cookbook.git'
cookbook 'nginxxx', git: 'https://github.com/linyows/nginx-cookbook.git'
